[package]
name = "portal"
version = "0.1.1"
authors = ["ilya sheprut <optozorax@gmail.com>"]
edition = "2018"

[dependencies]
# macroquad = { git = "https://github.com/not-fl3/macroquad", commit = "d2c1f0e" }
# macroquad-profiler = { git = "https://github.com/not-fl3/macroquad" }
macroquad = { path = "../macroquad" }
egui-macroquad = { path = "../../testing/egui-macroquad" }
glam = { version = "0.13.0", features = ["serde"] }
serde = "1.0.124"
serde_json = "1.0"
egui = "0.10.0"
fasteval = "0.2.4"
miniquad-parameters = { git = "https://github.com/optozorax/miniquad-parameters" }
# color-backtrace = "0.5.0"
